import React, { useState } from 'react';
import { OrderOperationsDemo } from './OrderOperationsDemo';
import { modules, capabilities, stages, gatewaySteps, safety, canonicalSource, contacts, identities, conversations, selectModule, initialSession, prepareSession, nextDay, legacyOrder, legacyDelivery, canonicalOrder, canonicalDelivery, sessionBudget } from './model';
import type { ModuleId } from './model';
import type { VisualSession } from '../offline-preview/scenario';

function Badge({ children }: { children: React.ReactNode }) { return <span className="badge">{children}</span>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="panel"><h2>{title}</h2>{children}</section>; }
function Facts({ rows }: { rows: readonly (readonly [string, string])[] }) { return <dl className="facts">{rows.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>; }
function StatusTable() { return <div className="table-scroll"><table><thead><tr><th>Capacidade</th><th>Fase</th><th>Status comprovado</th><th>Gap principal</th></tr></thead><tbody>{capabilities.map(c => <tr key={c.id}><td><strong>{c.title}</strong></td><td>{c.phase}</td><td><div className="badges">{c.statuses.map(s => <Badge key={s}>{s}</Badge>)}</div></td><td>{c.gap}</td></tr>)}</tbody></table></div>; }
function Dispatch({ session, update }: { session: VisualSession; update: (s: VisualSession) => void }) {
  const budget = sessionBudget(session); return <><div className="flow">{['MarketingCampaign', 'Audience', 'DispatchCampaign', 'Eligibility', 'Daily Budget', 'Queue', 'Draft'].map(x => <span key={x}>{x}</span>)}</div><div className="two"><Panel title="Dispatch · COMO + QUANDO"><Badge>SIMULATION / OFFLINE</Badge><Facts rows={[["Campanha", session.sales.campaign.id], ["Limite diário", "2 drafts · política local"], ["Público", "Ana, Bruno e Carla Exemplo"], ["Dia simulado", budget.day], ["Budget consumido", `${budget.used} / 2 drafts`], ["Budget restante", String(budget.remaining)], ["Mensagens enviadas", "0"]]}/><p>RCS desconhecido em Bruno usa alternativa WhatsApp. Carla permanece bloqueada. Janela real não avaliada.</p><div className="actions"><button className="primary" onClick={() => update(prepareSession(session))}>Preparar rascunhos sintéticos</button><button onClick={() => update(nextDay(session))}>Avançar dia simulado</button><button onClick={() => update(initialSession())}>Reiniciar cenário</button></div><p role="status" className="notice">{session.feedback}</p></Panel><Panel title="Fila e elegibilidade"><div className="table-scroll"><table><thead><tr><th>Posição</th><th>Contato</th><th>Estado</th><th>Canal do draft</th></tr></thead><tbody>{session.sales.queue.entries.map(e => <tr key={e.id}><td>{e.position}</td><td>{contacts.find(c => c.id === e.contactId)?.name}</td><td>{e.contactId === 'demo-contact-2' ? 'Bloqueado · sem draft' : e.status}</td><td>{session.sales.drafts.find(d => d.queueEntryId === e.id)?.channel ?? 'Não escolhido'}</td></tr>)}</tbody></table></div><p>Replay não duplica drafts nem consumo de orçamento. Não há botão de envio.</p></Panel></div>{session.sales.drafts.length > 0 && <Panel title="Rascunhos · não são mensagens enviadas">{session.sales.drafts.map(d => <article className="draft" key={d.id}><Badge>DRAFT · SIMULAÇÃO</Badge><p>{d.content}</p></article>)}</Panel>}</>;
}
function Orders() { return <><p className="warning">Pedidos unificados operacionalmente ainda incompletos. Caixa, cozinha e delivery continuam usando seus fluxos legados.</p><div className="two">{['Order legado', 'DeliveryOrder'].map(label => {
    // Explicit branches retain source/projection types without operational consumers.
    const delivery = label === 'DeliveryOrder'; const s = delivery ? legacyDelivery : legacyOrder; const p = delivery ? canonicalDelivery : canonicalOrder;
    return <Panel title={`${label} → Order canônico`} key={String(label)}><div className="comparison"><div><Badge>OPERAÇÃO LEGADA · FIXTURE</Badge><Facts rows={[["ID", s.id], ["Cliente", s.clientName], ["Status de exemplo", s.status], ["Total fictício", "R$ 40,00"]]}/></div><div><Badge>ADAPTER / OFFLINE</Badge><Facts rows={[["ID preservado", p.order.id], ["tenantId", p.order.tenantId], ["contactId", p.order.contactId], ["entryPoint", p.order.entryPoint], ["channel", p.order.channel], ["creationMode", p.order.creationMode], ["Status projetado", p.order.status], ["OrderItem", `${p.items.length} item · quantidade ${p.items[0].quantity}`]]}/></div></div><p>{delivery ? 'DeliveryOrder mantém status e dados próprios. Subtotal/quantidade projeta preço unitário.' : 'Order legado preservado; projeção não grava nem substitui a fonte.'}</p></Panel>;
  })}</div><Panel title="Falta integrar à operação"><p>Persistência, escrita, consumidores de caixa/KDS/delivery e equivalência de estados. CREATED/PAID/CANCELED não substituem automaticamente PRONTO, EM ENTREGA ou FECHADO.</p></Panel></>; }
function LegacyDemo({ module }: { module: ModuleId }) {
  const descriptions: Partial<Record<ModuleId, [string, string]>> = { cardapio: ['Prato Demo', 'Item fictício · R$ 20,00 · sem compra ou pedido'], caixa: ['Caixa / PDV · demonstração', 'Nenhuma sessão aberta, cobrança, pagamento ou receita registrada.'], cozinha: ['KDS · Pedido Demo', 'Quadro ilustrativo, sem ticket real e sem alteração de produção.'], delivery: ['DeliveryOrder · Pedido Demo', 'Bruno Exemplo · endereço fictício · nenhuma entrega realizada.'] };
  const item = descriptions[module]!;
  return <><div className="two"><Panel title="Operação original preservada"><Badge>OPERACIONAL LEGADO</Badge><p>O módulo existente pertence ao LidacomZapCRM. Esta tela apenas o representa com fixtures; não importa seus componentes nem executa sua lógica.</p><Badge>INTEGRAÇÃO COM NOVO DOMÍNIO PENDENTE</Badge></Panel><Panel title={item[0]}><Badge>DEMO · DADOS SINTÉTICOS</Badge><p>{item[1]}</p><div className="demo-ticket">Pedido Demo<br/><small>Somente representação visual</small></div></Panel></div></>;
}
export function ProductPreview({ initialModule = 'dashboard' }: { initialModule?: ModuleId }) {
  const [tab, setTab] = useState<ModuleId>(initialModule); const [session, setSession] = useState(initialSession);
  const nav = (id: string) => setTab(current => selectModule(current, id));
  const label = modules.find(m => m[0] === tab)![1];
  return <div className="shell"><aside className="sidebar"><div className="brand"><span className="brand-icon">L</span><div>LidacomZapCRM<small>Projeto unificado</small></div></div><div className="side-label">PREVIEW DO PRODUTO</div><nav aria-label="Módulos do produto">{modules.map(([id, title, icon]) => <button key={id} className={id === tab ? 'selected' : ''} aria-current={id === tab ? 'page' : undefined} onClick={() => nav(id)}><span aria-hidden="true">{icon}</span>{title}</button>)}</nav><div className="sidebar-foot">Um produto. Uma evolução.<br/>Operação + domínio incorporado.</div></aside><main><div className="safety"><strong>PREVIEW INTEGRADO — DADOS SINTÉTICOS</strong><span>Sem backend operacional · Nenhum envio real</span><Badge>MODE: OFFLINE PREVIEW</Badge></div><header><div><div className="eyebrow">LIDACOMZAPCRM / ESTADO ATUAL DO PRODUTO</div><h1>{tab === 'dashboard' ? 'LidacomZapCRM' : label}</h1><p>{tab === 'dashboard' ? 'Projeto unificado · operação preservada e arquitetura incorporada' : 'Demonstração local isolada · capacidades e limites reais'}</p></div><span className="snapshot">Mapa canônico<br/><strong>{canonicalSource}</strong></span></header>
  {tab === 'dashboard' && <><div className="summary"><div><strong>1</strong><span>produto unificado</span></div><div><strong>0</strong><span>mensagens enviadas</span></div><div><strong>19</strong><span>áreas demonstrativas</span></div><div><strong>Pendente</strong><span>staging do novo fluxo</span></div></div><div className="section-heading"><h2>Como o produto está ficando</h2><Badge>PREPARATION ≠ LIVE READY</Badge></div><div className="cards">{capabilities.slice(0, 11).map((c, index) => <button className="cap-card" key={c.id} onClick={() => nav(c.module)}><div className="cap-top"><span className="cap-icon">{index + 1 < 10 ? `0${index + 1}` : index + 1}</span><span className="arrow">↗</span></div><h2>{c.title}</h2><div className="badges">{c.statuses.map(s => <Badge key={s}>{s}</Badge>)}</div><small>{c.phase}</small><p>{c.gap}</p><span className="explore">Explorar módulo →</span></button>)}</div><p className="notice">Arquitetura/funcionalidades do Gestão incorporadas ao LidacomZapCRM. O repositório histórico permanece referência; este preview representa um único produto.</p></>}
  {(tab === 'crm' || tab === 'clientes') && <><div className="two"><Panel title="Client legado · CRM original"><Badge>OPERACIONAL LEGADO</Badge><p>Cadastros e operação existentes preservados. As fichas abaixo são somente exemplos e não foram carregadas do CRM.</p>{contacts.map(c => <article className="person" key={c.id}><span className="avatar">{c.name[0]}</span><div><strong>{c.name}</strong><small>Client legado · {c.id}</small></div><Badge>DEMO</Badge></article>)}</Panel><Panel title="Contact / ContactChannelIdentity"><Badge>CONTRATO / ADAPTER / OFFLINE</Badge>{contacts.map(c => <article className="identity" key={c.id}><strong>{c.name} · Contact</strong><small>tenant: {c.tenantId} · {c.id}</small><div className="badges">{identities.filter(i => i.contactId === c.id).map(i => <Badge key={i.id}>{i.channel} identity · {i.availability}</Badge>)}</div></article>)}<p>Availability é fixture, não consulta real. Integração operacional completa ainda não ocorreu.</p></Panel></div></>}
  {tab === 'conversas' && <><p className="warning">Conversas reais da UI atual: LEGADO / OPERACIONAL ORIGINAL. Inbox omnichannel real: PENDENTE.</p><div className="two"><Panel title="Ana Exemplo · Contact"><Badge>OFFLINE IMPLEMENTADO</Badge><div className="flow vertical">{conversations.map(c => <span key={c.id}>Contact → Conversation {c.channel}<small>{c.id}</small></span>)}</div><p>Um contato; duas conversas por canal. Sem união automática de históricos operacionais.</p></Panel><Panel title="Conversa ilustrativa"><Badge>DEMO · NÃO ENVIADA</Badge><p className="bubble">Olá, Ana Exemplo. Esta é uma conversa sintética para conhecer o produto.</p><p>Não há delivery/read/reply de provider. Este texto não cria mensagem ou receipt.</p></Panel></div></>}
  {tab === 'marketing' && <div className="two"><Panel title="MarketingCampaign · QUEM + POR QUÊ"><Badge>OFFLINE IMPLEMENTADO</Badge><Facts rows={[["Campanha", "Retorno de clientes — exemplo"], ["Público", "Ana, Bruno e Carla Exemplo"], ["Por quê", "Seleção manual para demonstração"], ["Audience", "Snapshot explícito, sintético"]]}/><p>Marketing define público e intenção. Pertencer ao público não autoriza preparação ou envio.</p></Panel><Panel title="DispatchCampaign · COMO + QUANDO"><Badge>DOMÍNIO SEPARADO</Badge><p>Estratégia de canal, template, orçamento diário e fila pertencem ao Dispatch. A transferência entre domínios já existe offline.</p><button className="primary" onClick={() => nav('dispatch')}>Ver preparação de Dispatch</button></Panel></div>}
  {(tab === 'venda' || tab === 'dispatch') && <Dispatch session={session} update={setSession}/>}
  {tab === 'funil' && <><p className="notice">Opportunity sintética somente em RASCUNHO após preparar drafts. Client.status ou Client.stage não são convertidos automaticamente. As demais colunas mostram o contrato, sem fatos fabricados.</p><div className="kanban">{stages.map(s => <section key={s}><h2>{s}</h2><Badge>{s === 'RASCUNHO' ? 'SIMULAÇÃO' : 'CONTRATO'}</Badge>{s === 'RASCUNHO' ? session.events.opportunities.map(o => <article key={o.id}><strong>{contacts.find(c => c.id === o.contactId)?.name}</strong><p>Opportunity · DRAFT</p></article>) : <p>Nenhum fato registrado</p>}</section>)}</div></>}
  {tab === 'conversas' && <OrderOperationsDemo/>}
  {tab === 'pedidos' && <><Orders/><OrderOperationsDemo/></>}
  {['cardapio', 'caixa', 'cozinha', 'delivery'].includes(tab) && <LegacyDemo module={tab}/>}
  {tab === 'timeline' && <Panel title="TimelineEvent · fatos da simulação"><Badge>OFFLINE / SINTÉTICO</Badge><p>Somente eventos gerados pelo preparo conhecido de drafts. Nenhum envio, delivery, read, reply, pedido ou receita real.</p>{session.events.timeline.length === 0 ? <div className="empty"><h3>Nenhum evento de draft ainda</h3><p>Prepare rascunhos na Venda Ativa para demonstrar a timeline.</p><button onClick={() => nav('venda')}>Abrir Venda Ativa</button></div> : session.events.timeline.map(e => <article className="event" key={e.id}><span className="event-dot"/><div><strong>{e.title}</strong><p>{e.description}</p><small>{contacts.find(c => c.id === e.contactId)?.name} · SIMULATION</small></div></article>)}</Panel>}
  {tab === 'whatsapp' && <div className="two"><Panel title="WhatsApp · preparação Meta"><Facts rows={[["Meta provider boundary", "OFFLINE IMPLEMENTADO"], ["MessagingWindowPolicy", "OFFLINE IMPLEMENTADO"], ["TemplatePolicy", "OFFLINE IMPLEMENTADO"], ["Inbound", "OFFLINE IMPLEMENTADO"], ["Worker", "OFFLINE / SINTÉTICO"], ["Transport", "DISABLED"], ["Staging", "PENDENTE"], ["Live", "PENDENTE"], ["Mensagens enviadas", "0"]]}/></Panel><Panel title="Janela e limites"><Badge>ENVIO BLOQUEADO</Badge><p>Inbound verificado pode fundamentar a janela de 24 horas no domínio. Evidência ausente permanece UNKNOWN. Outbound não renova a janela.</p><p>Templates exigem aprovação e vínculo de tenant/provider/modo. Neste preview nenhuma policy recebe evidência real, e nenhum provider é importado.</p><p className="warning">Primeiro envio continua em GATE_OUTBOUND_CANARY_REQUIRED.</p></Panel></div>}
  {tab === 'rcs' && <div className="two"><Panel title="Google RCS · boundary preparada"><Facts rows={[["RCS Provider", "DISABLED"], ["Capability", "UNKNOWN / fixture"], ["Drafts", "MOCK"], ["Fallback", "OFFLINE IMPLEMENTADO"], ["Google RCS Agent", "NÃO CONFIGURADO"], ["Live", "PENDENTE"], ["Mensagens enviadas", "0"]]}/></Panel><Panel title="Um canal por preparação"><Badge>OFFLINE IMPLEMENTADO</Badge><p>Fallback avalia disponibilidade, elegibilidade e política. ACCEPTED ou UNCERTAIN bloqueiam nova tentativa entre canais.</p><p>Drafts internos não são protocolo Google serializado. Nenhuma consulta Google, scraping ou import de provider ocorre aqui.</p></Panel></div>}
  {tab === 'gateway' && <><div className="flow vertical gateway">{gatewaySteps.map(s => <span key={s}>{s}</span>)}</div><div className="two"><Panel title="Estado atual"><Badge>LOCAL / SYNTHETIC</Badge><p>Admission/journal, lease, worker e resolução foram implementados e testados localmente. Este desenho apenas representa a arquitetura; não inicia listener ou worker.</p><p>Resposta automática: DRAFT somente, com escalonamento humano. Auto-send: bloqueado.</p></Panel><Panel title="Próxima camada"><Badge>STG-03 · SOMENTE TEST / IAM PRIVADO</Badge><p>Firestore staging para fixtures TEST: transações, replay e recuperação validados. Este preview não conecta essa base.</p><p>HTTPS e worker privados de fixtures TEST comprovados na STG-03. Receiver público e configuração Meta real pendentes; RCS DISABLED.</p></Panel></div></>}
  {tab === 'config' && <div className="two"><Panel title="Ambiente do preview"><Facts rows={[["MODE", safety.mode], ["Backend", safety.backend], ["Dados", "FIXTURES SINTÉTICAS"], ["Persistência", "Memória da sessão"], ["Envio", "BLOQUEADO"], ["MODE: STAGING", "PENDENTE · não ativável aqui"]]}/></Panel><Panel title="Gates preservados"><Badge>STG-01 · HOSTING ISOLADO VALIDADO</Badge><p>Firebase staging separado e Hosting pr-4 com CI federada comprovados. Este preview continua sintético, sem backend. Não existe seletor de integração real.</p><Badge>GATE_META_TRUSTED_DEVICE_REQUIRED</Badge><p>STG-03 privado TEST concluído; billing staging autorizado anteriormente. Meta real pausada por dispositivo não reconhecido, sem novas tentativas.</p><Badge>GATE_OUTBOUND_CANARY_REQUIRED</Badge><p>Autorizar um ambiente não autoriza o primeiro envio. Providers continuam DISABLED.</p></Panel></div>}
  {tab === 'arquitetura' && <Panel title="Estado do Produto"><p>Mapa local derivado manualmente do documento canônico. Uma tela demonstrativa não promove capacidade a operacional. Nenhuma capacidade nova é STAGING READY, LIVE READY ou OPERACIONAL COMPLETO.</p><StatusTable/></Panel>}
  <footer>PREVIEW INTEGRADO — DADOS SINTÉTICOS · Nenhuma operação altera produção · Nenhum envio real · Sem backend operacional</footer></main></div>;
}
